library(ggplot2)
df <- as.data.frame(table(mtcars$cyl))
colnames(df) <- c('cyl','count')
p <- ggplot(df, aes(x=factor(cyl), y=count)) + geom_bar(stat='identity', fill='steelblue') + labs(x='Cilindros')
print(p)
ggsave('grafico.png', plot = p)