library(ggplot2)
df <- data.frame(group=c('A'), v1=4, v2=3, v3=5, v4=2)
dfm <- as.data.frame(rbind(rep(5,4), rep(0,4), df[,-1]))
colnames(dfm) <- c('v1','v2','v3','v4')
dfm$group <- c('max','min', 'A')
long <- reshape2::melt(dfm, id.vars='group')
p <- ggplot(long[long$group=='A',], aes(x=variable, y=value, group=1)) + geom_polygon(fill='lightblue', alpha=0.5) + coord_polar()
print(p)
ggsave('grafico.png', plot = p)